### ISSUE TITLE
add fortran-tutorial tag

### ISSUE THREAD

**Issue by Beliavsky** [gjbex/Fortran-MOOC#7]
Could you add the tag fortran-tutorial to your project? If all relevant repos add this tag it will make such material easier to find on GitHub. Currently topics such javascript-tutorial and python-tutorial have many entries. Fortran-tutorial has 2.

**Comment by gjbex** [comment]
@Beliavsky Sure, done.  Thanks for the tip, I had indeed forgotten to add tags.
